### PR TITLE
Re: Pull Request

### PR DESCRIPTION
**Pull request by SF-Rocker**
Quote:

@SF-Rocker thanks! Send PR to https://github.com/ZhymabekRoman/puffin-internet-terminal-arch

### CODE REVIEW

**Comment by ZhymabekRoman** [comment]
Thanks! Done! Available at https://aur.archlinux.org/packages/puffin-internet-terminal-bin and https://aur.archlinux.org/packages/puffin-internet-terminal-demo-bin

**Comment by SF-Rocker** [comment]
i try to install it with yay and choose No and 1 and it shows this:

`AUR Explicit (1): puffin-internet-terminal-demo-bin-8.2.4.705-1
:: PKGBUILD up to date, skipping download: puffin-internet-terminal-demo-bin
  1 puffin-internet-terminal-demo-bin        (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> ^C
[sfrocker@sfrocker-pc ~]$ cd Downloads
[sfrocker@sfrocker-pc Downloads]$ ls
Puffin-Internet-Terminal-Demo
[sfrocker@sfrocker-pc Downloads]$ yay -S puffin-internet-terminal-demo-bin
AUR Explicit (1): puffin-internet-terminal-demo-bin-8.2.4.705-1
:: PKGBUILD up to date, skipping download: puffin-internet-terminal-demo-bin
  1 puffin-internet-terminal-demo-bin        (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 2
  1 puffin-internet-terminal-demo-bin        (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 2
==> ERROR: puffin-internet-terminal-demo-bin is not available for the 'aarch64' architecture.
 -> error downloading sources: /home/sfrocker/.cache/yay/puffin-internet-terminal-demo-bin 
         context: exit status 12 
         

:: (1/1) Parsing SRCINFO: puffin-internet-terminal-demo-bin
 -> The following packages are not compatible with your architecture:
  puffin-internet-terminal-demo-bin
:: Try to build them anyway? [Y/n] n
 -> aborting due to user
[sfrocker@sfrocker-pc Downloads]$ yay -S puffin-internet-terminal-demo-bin
AUR Explicit (1): puffin-internet-terminal-demo-bin-8.2.4.705-1
:: PKGBUILD up to date, skipping download: puffin-internet-terminal-demo-bin
  1 puffin-internet-terminal-demo-bin        (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> No
  1 puffin-internet-terminal-demo-bin        (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 1
diff --git /home/sfrocker/.cache/yay/puffin-internet-terminal-demo-bin/PKGBUILD /home/sfrocker/.cache/yay/puffin-internet-terminal-demo-bin/PKGBUILD
new file mode 100644
index 0000000..67af3cc
--- /dev/null
+++ /home/sfrocker/.cache/yay/puffin-internet-terminal-demo-bin/PKGBUILD
@@ -0,0 +1,34 @@
+# Maintainer: Zhymabek Roman
+pkgname=puffin-internet-terminal-demo-bin
+pkgver=8.2.4.705
+pkgrel=1
+pkgdesc="The wicked fast web browser from CloudMosa Inc."
+arch=(x86_64 i686)
+url="https://www.puffin.com/"
+license=('custom')
+groups=()
+depends=()
+makedepends=()
+checkdepends=()
+optdepends=()
+provides=()
+conflicts=()
+replaces=()
+backup=()
+options=()
+install=
+changelog=
+noextract=()
+source_x86_64=("https://download.puffinbrowser.com/repo/pool/stable/amd64/puffin-internet-terminal-demo_${pkgver}_amd64.deb")
+source_i686=("https://download.puffinbrowser.com/repo/pool/stable/i386/puffin-internet-terminal-demo_${pkgver}_i386.deb")
+sha256sums_x86_64=('bc94930c3678c11cd94486fd03d03adcc4e9cea4e440f3b4b26dffd9abc59284')
+sha256sums_i686=('f68184307eb7fefc0c620d986673e31b8ca94f195972659a483251189e4d1d1e')
+validpgpkeys=()
+
+package() {
+  cd "$srcdir"
+  tar xf data.tar.xz -C "${pkgdir}"
+  chmod 755 "${pkgdir}/opt/" "${pkgdir}/usr" "${pkgdir}/usr/bin/" "${pkgdir}/usr/share/" "${pkgdir}/usr/share/applications" "${pkgdir}/usr/share/appdata"
+  rm "${pkgdir}/opt/cloudmosa/puffin_demo/upgrade" "${pkgdir}/opt/cloudmosa/puffin_demo/upgrade_agent"
+  ln -s "${pkgdit}"/opt/cloudmosa/puffin_demo/puffin_demo "${pkgdir}"/usr/bin/puffin_demo
+}
(END)
`

**Comment by SF-Rocker** [comment]
but the tar ball file does work

**Comment by ZhymabekRoman** [comment]
Hmmm, that's strange, I will check this issue

**Comment by ZhymabekRoman** [comment]
Probably yay uses cache, because if we check git diff with web anything alright: https://aur.archlinux.org/cgit/aur.git/diff/?h=puffin-internet-terminal-demo-bin

P.s. I have assumption why this happens: I forgot to increase pkgrel value in demo version of puffin :/

**Comment by SF-Rocker** [comment]
that's okay, i can install it manually i appreciate your support, if its not too hard to do idk i think you can edit it there.
==> ERROR: puffin-internet-terminal-demo-bin is not available for the 'aarch64' architecture.
 -> error downloading sources: /home/sfrocker/.cache/yay/puffin-internet-terminal-demo-bin 
         context: exit status 12 
         

:: (1/1) Parsing SRCINFO: puffin-internet-terminal-demo-bin
 -> The following packages are not compatible with your architecture:
  puffin-internet-terminal-demo-bin
:: Try to build them anyway? [Y/n] 
yeah idk why it would still do that you updated everything correctly.

**Comment by SF-Rocker** [comment]
this is what CHATGPT3.5 said about the package not being updated.
The PKGBUILD file itself doesn't update the Yay repository directly. 
Instead, updating a package in the Arch Linux AUR (Arch User Repository)
 using Yay involves a series of steps:

    Edit the PKGBUILD: You've edited the PKGBUILD file 
to update the package's version, source URLs, checksums, 
and other relevant information.

    Build the Package: After editing the PKGBUILD, you can use Yay to build the package.
 Yay will download the source files, compile the package,
 and create a binary package that can be installed.

    Install the Updated Package: Once the package is built,
 you can install the updated package using Yay.
 Yay will handle the installation process, 
which may involve uninstalling the old package and installing the new one.

    Push the Updated PKGBUILD to AUR: This step is not directly handled by Yay 
but is important for the broader Arch Linux community.
 If you want to make your PKGBUILD update available to others,
 you can upload it to the Arch User Repository (AUR). 
You'll need an AUR helper like Yay to assist with this step. Here's how you can do it:
        After you've tested the updated package, 
you can use `yay -G packagename` to clone the AUR package into a directory.
        Replace the PKGBUILD file in that directory with your updated version.
        Run `makepkg -si `inside the directory to build and install the package.
        Finally, use `yay --editmenu -S packagename` to submit the updated PKGBUILD to AUR.

After these steps, your updated PKGBUILD will be available for others to install and maintain.

Keep in mind that it's important to follow Arch Linux AUR guidelines
 and ensure that your PKGBUILD is correct and that the package builds 
and installs without issues before updating it in the AUR.

**Comment by ZhymabekRoman** [comment]
Try install full version of Puffin. If there is no problem I will increase pkgrel value of demo puffin

**Comment by SF-Rocker** [comment]
i installed the tarball but it does not have icons neither does demo.

**Comment by SF-Rocker** [comment]
full

**Comment by SF-Rocker** [comment]
demo

**Comment by SF-Rocker** [comment]
neofetch

**Comment by SF-Rocker** [comment]
i just added puffin ico file from google

**Comment by ZhymabekRoman** [comment]
Okey, I will try to add icon to Puffin. To install using yay please clean cache:
```
rm -rfv ~/.cache/yay/
```

**Comment by SF-Rocker** [comment]
okay it works very well thank you

**Comment by SF-Rocker** [comment]
Hello, i am trying to work on getting addressing the opt and usr folder with the application menu .desktop file because there is no image loading on my end i don't know if POSTINSTALL is messed up or if its just not extracting the files and reading where it is going at the same time, for example once the makepkg sees icon=puffinbrowserimage, it does not recognize the source directory, so there is nothing that i can do that fixes that, so manually i have to download the puffin image and put on my desktop application menu entry manually.

**Comment by ZhymabekRoman** [comment]
Thank you very much! I opened a new issue #2. For now, I don't know how to fix this

**Pull request merged**
